<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use HasFactory;

    protected $table = 'documents';

    protected $fillable = [
        'slug',
        'type',
        'description',
        'label_ar',
        'label_fr',
        'label_en',
        'template_path',
        'requires_return'
    ];

    // Document types
    const TYPE_GENERATED = 'GENERATED';  // Faculty creates (Attestation, Relevé)
    const TYPE_DEPOSITED = 'DEPOSITED';  // Student owns, faculty holds (Bac, Licence)

    /**
     * Check if document is generated by faculty
     */
    public function isGenerated(): bool
    {
        return $this->type === self::TYPE_GENERATED;
    }

    /**
     * Check if document is deposited by student
     */
    public function isDeposited(): bool
    {
        return $this->type === self::TYPE_DEPOSITED;
    }

    /**
     * Get type label in French
     */
    public function getTypeLabelAttribute(): string
    {
        return match ($this->type) {
            self::TYPE_GENERATED => 'Généré',
            self::TYPE_DEPOSITED => 'Déposé',
            default => 'Inconnu',
        };
    }

    // Relationships
    public function demandes()
    {
        return $this->hasMany(Demande::class, 'document_id');
    }
}
